### ISSUE TITLE
Running v1.1.6 on Ubuntu for the first time fails

### ISSUE THREAD

**Issue by ShahimEssaid** [monarch-initiative/loinc2hpo#101]
/usr/lib/jvm/java-8-oracle/bin/java -jar Loinc2HpoGui-jar-with-dependencies.jar
.....
java.io.FileNotFoundException: /home/shahim/.loinc2hpo/loinc2hpo.settings (No such file or directory)

This is on Ubuntu 19.04 with version v1.1.6 built locally. I've never ran the GUI before on this machine. the .loinc2hpo was created but a new settings file isn't being created.

**Comment by kingmanzhang** [comment]
Hi Shahim, I have not tested it on Linux. I will try it and get back to you.

**Comment by kingmanzhang** [comment]
At the same time, I suggest you try the compiled version:
https://github.com/monarch-initiative/loinc2hpo/releases/tag/v1.1.6

**Comment by kingmanzhang** [comment]
Could you post the entire stack trace? Thanks!

**Comment by ShahimEssaid** [comment]
<pre>
May 15, 2019 8:21:18 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 9 by JavaFX runtime of version 8.0.201
May 15, 2019 8:21:18 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 9 by JavaFX runtime of version 8.0.201
May 15, 2019 8:21:19 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 9 by JavaFX runtime of version 8.0.201
[JavaFX-Launcher] TRACE (Loinc2HpoAnnotationsTabController.java:70) - Calling initialize
May 15, 2019 8:21:19 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 9 by JavaFX runtime of version 8.0.201
java.io.FileNotFoundException: /home/shahim/.loinc2hpo/loinc2hpo.settings (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at org.monarchinitiative.loinc2hpo.model.Settings.loadSettings(Settings.java:50)
	at org.monarchinitiative.loinc2hpo.controller.MainController.initialize(MainController.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2566)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3214)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3175)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3165)
	at org.monarchinitiative.loinc2hpo.gui.Main.init(Main.java:54)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:841)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$412(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
2019-05-15 20:21:19,618 pool-2-thread-1 DEBUG Stopping LoggerContext[name=33909752, org.apache.logging.log4j.core.LoggerContext@23f7375a]
2019-05-15 20:21:19,618 pool-2-thread-1 DEBUG Stopping LoggerContext[name=33909752, org.apache.logging.log4j.core.LoggerContext@23f7375a]...
</pre>

**Comment by kingmanzhang** [comment]
Hi Shahim, this is really puzzling to me. Sorry, I don't have a clue why it could not create this file on your machine. Again, I have to go home and test whether I can reproduce the error message. At the present, I think one solution is to create the file yourself :
```
touch /home/shahim/.loinc2hpo/loinc2hpo.settings
```
Then start the compile app. I hope this would at least let you start it.

**Comment by kingmanzhang** [comment]
Close this for now. Will also release a docker image in a few month.
