### ISSUE TITLE
Error parsing the annotation map

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/loinc2hpo#115]
I get this error when starting the GUI
```
Exception in thread "JavaFX-Launcher" java.lang.RuntimeException: Error parsing the annotation map
	at org.monarchinitiative.loinc2hpogui.model.AppResources.getLoincAnnotationMap(AppResources.java:111)
	at org.monarchinitiative.loinc2hpogui.controller.MainController.lambda$initialize$0(MainController.java:118)
```

**Comment by kingmanzhang** [comment]
sorry to hear this! I suggest two things, 1) pull loinc2hpoAnnotation, checkout develop branch and try the app again; 2) delete the .loinc2hpo file in your home directory and restart the app (follow https://github.com/TheJacksonLaboratory/loinc2hpoAnnotation#set-up).
